import os
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from app.core.config import settings
from app.models.scan import Scan
from app.models.report import Report
from app.models.patient import Patient

class ReportService:
    @staticmethod
    def generate_scan_report(db: Session, scan: Scan) -> Report:
        """Compiles clinical report text, writes it to a file in reports/, and saves database record."""
        # 1. Fetch patient profile details to embed in report
        patient = db.query(Patient).filter(Patient.id == scan.patient_id).first()
        patient_name = patient.full_name if patient else "N/A"
        patient_age = patient.age if patient else "N/A"
        patient_gender = patient.gender if patient else "N/A"
        medical_history = patient.medical_history if patient else "N/A"

        utc_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # 2. Formulate structured diagnostics text
        report_text = (
            "======================================================================\n"
            "         AI-ASSISTED HISTOPATHOLOGY CANCER SCREENING REPORT\n"
            "======================================================================\n\n"
            f"Screening Date/Time : {utc_time}\n"
            f"Inference Model     : {scan.model_name}\n"
            "----------------------------------------------------------------------\n"
            "PATIENT PROFILE INFO\n"
            "----------------------------------------------------------------------\n"
            f"Patient ID          : {scan.patient_id}\n"
            f"Patient Full Name   : {patient_name}\n"
            f"Patient Age         : {patient_age}\n"
            f"Patient Gender      : {patient_gender}\n"
            f"Medical History     : {medical_history}\n\n"
            "----------------------------------------------------------------------\n"
            "CLINICAL AI PATHOLOGY FINDINGS\n"
            "----------------------------------------------------------------------\n"
            f"Scan Reference ID   : {scan.id}\n"
            f"Classification      : {scan.prediction.upper()}\n"
            f"Confidence Score    : {scan.confidence * 100:.2f}%\n"
            f"Uploaded Biopsy Path: {scan.image_path}\n"
            f"Grad-CAM Overlay    : {scan.heatmap_path}\n\n"
            "----------------------------------------------------------------------\n"
            "CLINICAL DISCLAIMER & WARNINGS (IMPORTANT)\n"
            "----------------------------------------------------------------------\n"
            "DISCLAIMER: This report is generated by a computer vision model as an\n"
            "AI-assisted screening support tool. It does NOT constitute a medical\n"
            "diagnosis. All scan interpretations, visualizations, and diagnostic\n"
            "outcomes must be reviewed, verified, and signed off by a qualified\n"
            "clinical pathologist. Do not base patient treatments solely on this output.\n"
            "======================================================================\n"
        )

        # 3. Ensure storage folders exist
        settings.report_dir_path.mkdir(parents=True, exist_ok=True)

        # 4. Save report file locally
        filename = f"report_scan_{scan.id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        file_path = settings.report_dir_path / filename

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(report_text)
        except Exception as e:
            raise RuntimeError(f"Failed writing clinical report text file: {str(e)}")

        # 5. Insert record in reports table
        db_report = Report(
            scan_id=scan.id,
            report_text=report_text
        )
        db.add(db_report)
        db.commit()
        db.refresh(db_report)

        return db_report
